package me.ele.napos.mybatis.model;

import java.util.Date;

public class EleKeeper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.status
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.username
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.password
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.mobile
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.mail
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.realname
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.image_hash
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String imageHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.title
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.created_at
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.updated_at
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_keeper.last_acted_time
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Date lastActedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.id
     *
     * @return the value of ele_keeper.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.id
     *
     * @param id the value for ele_keeper.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.type
     *
     * @return the value of ele_keeper.type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.type
     *
     * @param type the value for ele_keeper.type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.status
     *
     * @return the value of ele_keeper.status
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.status
     *
     * @param status the value for ele_keeper.status
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.username
     *
     * @return the value of ele_keeper.username
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.username
     *
     * @param username the value for ele_keeper.username
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.password
     *
     * @return the value of ele_keeper.password
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.password
     *
     * @param password the value for ele_keeper.password
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.mobile
     *
     * @return the value of ele_keeper.mobile
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.mobile
     *
     * @param mobile the value for ele_keeper.mobile
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.mail
     *
     * @return the value of ele_keeper.mail
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.mail
     *
     * @param mail the value for ele_keeper.mail
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.realname
     *
     * @return the value of ele_keeper.realname
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.realname
     *
     * @param realname the value for ele_keeper.realname
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.image_hash
     *
     * @return the value of ele_keeper.image_hash
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getImageHash() {
        return imageHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.image_hash
     *
     * @param imageHash the value for ele_keeper.image_hash
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setImageHash(String imageHash) {
        this.imageHash = imageHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.title
     *
     * @return the value of ele_keeper.title
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.title
     *
     * @param title the value for ele_keeper.title
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.created_at
     *
     * @return the value of ele_keeper.created_at
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.created_at
     *
     * @param createdAt the value for ele_keeper.created_at
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.updated_at
     *
     * @return the value of ele_keeper.updated_at
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.updated_at
     *
     * @param updatedAt the value for ele_keeper.updated_at
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_keeper.last_acted_time
     *
     * @return the value of ele_keeper.last_acted_time
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Date getLastActedTime() {
        return lastActedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_keeper.last_acted_time
     *
     * @param lastActedTime the value for ele_keeper.last_acted_time
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setLastActedTime(Date lastActedTime) {
        this.lastActedTime = lastActedTime;
    }
}