package me.ele.napos.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class EleShikigamiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public EleShikigamiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCvIsNull() {
            addCriterion("cv is null");
            return (Criteria) this;
        }

        public Criteria andCvIsNotNull() {
            addCriterion("cv is not null");
            return (Criteria) this;
        }

        public Criteria andCvEqualTo(String value) {
            addCriterion("cv =", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotEqualTo(String value) {
            addCriterion("cv <>", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvGreaterThan(String value) {
            addCriterion("cv >", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvGreaterThanOrEqualTo(String value) {
            addCriterion("cv >=", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvLessThan(String value) {
            addCriterion("cv <", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvLessThanOrEqualTo(String value) {
            addCriterion("cv <=", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvLike(String value) {
            addCriterion("cv like", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotLike(String value) {
            addCriterion("cv not like", value, "cv");
            return (Criteria) this;
        }

        public Criteria andCvIn(List<String> values) {
            addCriterion("cv in", values, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotIn(List<String> values) {
            addCriterion("cv not in", values, "cv");
            return (Criteria) this;
        }

        public Criteria andCvBetween(String value1, String value2) {
            addCriterion("cv between", value1, value2, "cv");
            return (Criteria) this;
        }

        public Criteria andCvNotBetween(String value1, String value2) {
            addCriterion("cv not between", value1, value2, "cv");
            return (Criteria) this;
        }

        public Criteria andAttackNumIsNull() {
            addCriterion("attack_num is null");
            return (Criteria) this;
        }

        public Criteria andAttackNumIsNotNull() {
            addCriterion("attack_num is not null");
            return (Criteria) this;
        }

        public Criteria andAttackNumEqualTo(String value) {
            addCriterion("attack_num =", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumNotEqualTo(String value) {
            addCriterion("attack_num <>", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumGreaterThan(String value) {
            addCriterion("attack_num >", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumGreaterThanOrEqualTo(String value) {
            addCriterion("attack_num >=", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumLessThan(String value) {
            addCriterion("attack_num <", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumLessThanOrEqualTo(String value) {
            addCriterion("attack_num <=", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumLike(String value) {
            addCriterion("attack_num like", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumNotLike(String value) {
            addCriterion("attack_num not like", value, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumIn(List<String> values) {
            addCriterion("attack_num in", values, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumNotIn(List<String> values) {
            addCriterion("attack_num not in", values, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumBetween(String value1, String value2) {
            addCriterion("attack_num between", value1, value2, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackNumNotBetween(String value1, String value2) {
            addCriterion("attack_num not between", value1, value2, "attackNum");
            return (Criteria) this;
        }

        public Criteria andAttackTypeIsNull() {
            addCriterion("attack_type is null");
            return (Criteria) this;
        }

        public Criteria andAttackTypeIsNotNull() {
            addCriterion("attack_type is not null");
            return (Criteria) this;
        }

        public Criteria andAttackTypeEqualTo(String value) {
            addCriterion("attack_type =", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeNotEqualTo(String value) {
            addCriterion("attack_type <>", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeGreaterThan(String value) {
            addCriterion("attack_type >", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeGreaterThanOrEqualTo(String value) {
            addCriterion("attack_type >=", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeLessThan(String value) {
            addCriterion("attack_type <", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeLessThanOrEqualTo(String value) {
            addCriterion("attack_type <=", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeLike(String value) {
            addCriterion("attack_type like", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeNotLike(String value) {
            addCriterion("attack_type not like", value, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeIn(List<String> values) {
            addCriterion("attack_type in", values, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeNotIn(List<String> values) {
            addCriterion("attack_type not in", values, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeBetween(String value1, String value2) {
            addCriterion("attack_type between", value1, value2, "attackType");
            return (Criteria) this;
        }

        public Criteria andAttackTypeNotBetween(String value1, String value2) {
            addCriterion("attack_type not between", value1, value2, "attackType");
            return (Criteria) this;
        }

        public Criteria andLivesNumIsNull() {
            addCriterion("lives_num is null");
            return (Criteria) this;
        }

        public Criteria andLivesNumIsNotNull() {
            addCriterion("lives_num is not null");
            return (Criteria) this;
        }

        public Criteria andLivesNumEqualTo(String value) {
            addCriterion("lives_num =", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumNotEqualTo(String value) {
            addCriterion("lives_num <>", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumGreaterThan(String value) {
            addCriterion("lives_num >", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumGreaterThanOrEqualTo(String value) {
            addCriterion("lives_num >=", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumLessThan(String value) {
            addCriterion("lives_num <", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumLessThanOrEqualTo(String value) {
            addCriterion("lives_num <=", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumLike(String value) {
            addCriterion("lives_num like", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumNotLike(String value) {
            addCriterion("lives_num not like", value, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumIn(List<String> values) {
            addCriterion("lives_num in", values, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumNotIn(List<String> values) {
            addCriterion("lives_num not in", values, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumBetween(String value1, String value2) {
            addCriterion("lives_num between", value1, value2, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesNumNotBetween(String value1, String value2) {
            addCriterion("lives_num not between", value1, value2, "livesNum");
            return (Criteria) this;
        }

        public Criteria andLivesTypeIsNull() {
            addCriterion("lives_type is null");
            return (Criteria) this;
        }

        public Criteria andLivesTypeIsNotNull() {
            addCriterion("lives_type is not null");
            return (Criteria) this;
        }

        public Criteria andLivesTypeEqualTo(String value) {
            addCriterion("lives_type =", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeNotEqualTo(String value) {
            addCriterion("lives_type <>", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeGreaterThan(String value) {
            addCriterion("lives_type >", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeGreaterThanOrEqualTo(String value) {
            addCriterion("lives_type >=", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeLessThan(String value) {
            addCriterion("lives_type <", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeLessThanOrEqualTo(String value) {
            addCriterion("lives_type <=", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeLike(String value) {
            addCriterion("lives_type like", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeNotLike(String value) {
            addCriterion("lives_type not like", value, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeIn(List<String> values) {
            addCriterion("lives_type in", values, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeNotIn(List<String> values) {
            addCriterion("lives_type not in", values, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeBetween(String value1, String value2) {
            addCriterion("lives_type between", value1, value2, "livesType");
            return (Criteria) this;
        }

        public Criteria andLivesTypeNotBetween(String value1, String value2) {
            addCriterion("lives_type not between", value1, value2, "livesType");
            return (Criteria) this;
        }

        public Criteria andDefenseNumIsNull() {
            addCriterion("defense_num is null");
            return (Criteria) this;
        }

        public Criteria andDefenseNumIsNotNull() {
            addCriterion("defense_num is not null");
            return (Criteria) this;
        }

        public Criteria andDefenseNumEqualTo(String value) {
            addCriterion("defense_num =", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumNotEqualTo(String value) {
            addCriterion("defense_num <>", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumGreaterThan(String value) {
            addCriterion("defense_num >", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumGreaterThanOrEqualTo(String value) {
            addCriterion("defense_num >=", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumLessThan(String value) {
            addCriterion("defense_num <", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumLessThanOrEqualTo(String value) {
            addCriterion("defense_num <=", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumLike(String value) {
            addCriterion("defense_num like", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumNotLike(String value) {
            addCriterion("defense_num not like", value, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumIn(List<String> values) {
            addCriterion("defense_num in", values, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumNotIn(List<String> values) {
            addCriterion("defense_num not in", values, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumBetween(String value1, String value2) {
            addCriterion("defense_num between", value1, value2, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseNumNotBetween(String value1, String value2) {
            addCriterion("defense_num not between", value1, value2, "defenseNum");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeIsNull() {
            addCriterion("defense_type is null");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeIsNotNull() {
            addCriterion("defense_type is not null");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeEqualTo(String value) {
            addCriterion("defense_type =", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeNotEqualTo(String value) {
            addCriterion("defense_type <>", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeGreaterThan(String value) {
            addCriterion("defense_type >", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("defense_type >=", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeLessThan(String value) {
            addCriterion("defense_type <", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeLessThanOrEqualTo(String value) {
            addCriterion("defense_type <=", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeLike(String value) {
            addCriterion("defense_type like", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeNotLike(String value) {
            addCriterion("defense_type not like", value, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeIn(List<String> values) {
            addCriterion("defense_type in", values, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeNotIn(List<String> values) {
            addCriterion("defense_type not in", values, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeBetween(String value1, String value2) {
            addCriterion("defense_type between", value1, value2, "defenseType");
            return (Criteria) this;
        }

        public Criteria andDefenseTypeNotBetween(String value1, String value2) {
            addCriterion("defense_type not between", value1, value2, "defenseType");
            return (Criteria) this;
        }

        public Criteria andSpeedNumIsNull() {
            addCriterion("speed_num is null");
            return (Criteria) this;
        }

        public Criteria andSpeedNumIsNotNull() {
            addCriterion("speed_num is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedNumEqualTo(String value) {
            addCriterion("speed_num =", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumNotEqualTo(String value) {
            addCriterion("speed_num <>", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumGreaterThan(String value) {
            addCriterion("speed_num >", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumGreaterThanOrEqualTo(String value) {
            addCriterion("speed_num >=", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumLessThan(String value) {
            addCriterion("speed_num <", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumLessThanOrEqualTo(String value) {
            addCriterion("speed_num <=", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumLike(String value) {
            addCriterion("speed_num like", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumNotLike(String value) {
            addCriterion("speed_num not like", value, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumIn(List<String> values) {
            addCriterion("speed_num in", values, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumNotIn(List<String> values) {
            addCriterion("speed_num not in", values, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumBetween(String value1, String value2) {
            addCriterion("speed_num between", value1, value2, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedNumNotBetween(String value1, String value2) {
            addCriterion("speed_num not between", value1, value2, "speedNum");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeIsNull() {
            addCriterion("speed_type is null");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeIsNotNull() {
            addCriterion("speed_type is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeEqualTo(String value) {
            addCriterion("speed_type =", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeNotEqualTo(String value) {
            addCriterion("speed_type <>", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeGreaterThan(String value) {
            addCriterion("speed_type >", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeGreaterThanOrEqualTo(String value) {
            addCriterion("speed_type >=", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeLessThan(String value) {
            addCriterion("speed_type <", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeLessThanOrEqualTo(String value) {
            addCriterion("speed_type <=", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeLike(String value) {
            addCriterion("speed_type like", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeNotLike(String value) {
            addCriterion("speed_type not like", value, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeIn(List<String> values) {
            addCriterion("speed_type in", values, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeNotIn(List<String> values) {
            addCriterion("speed_type not in", values, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeBetween(String value1, String value2) {
            addCriterion("speed_type between", value1, value2, "speedType");
            return (Criteria) this;
        }

        public Criteria andSpeedTypeNotBetween(String value1, String value2) {
            addCriterion("speed_type not between", value1, value2, "speedType");
            return (Criteria) this;
        }

        public Criteria andCriticalNumIsNull() {
            addCriterion("critical_num is null");
            return (Criteria) this;
        }

        public Criteria andCriticalNumIsNotNull() {
            addCriterion("critical_num is not null");
            return (Criteria) this;
        }

        public Criteria andCriticalNumEqualTo(String value) {
            addCriterion("critical_num =", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumNotEqualTo(String value) {
            addCriterion("critical_num <>", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumGreaterThan(String value) {
            addCriterion("critical_num >", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumGreaterThanOrEqualTo(String value) {
            addCriterion("critical_num >=", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumLessThan(String value) {
            addCriterion("critical_num <", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumLessThanOrEqualTo(String value) {
            addCriterion("critical_num <=", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumLike(String value) {
            addCriterion("critical_num like", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumNotLike(String value) {
            addCriterion("critical_num not like", value, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumIn(List<String> values) {
            addCriterion("critical_num in", values, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumNotIn(List<String> values) {
            addCriterion("critical_num not in", values, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumBetween(String value1, String value2) {
            addCriterion("critical_num between", value1, value2, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalNumNotBetween(String value1, String value2) {
            addCriterion("critical_num not between", value1, value2, "criticalNum");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeIsNull() {
            addCriterion("critical_type is null");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeIsNotNull() {
            addCriterion("critical_type is not null");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeEqualTo(String value) {
            addCriterion("critical_type =", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeNotEqualTo(String value) {
            addCriterion("critical_type <>", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeGreaterThan(String value) {
            addCriterion("critical_type >", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeGreaterThanOrEqualTo(String value) {
            addCriterion("critical_type >=", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeLessThan(String value) {
            addCriterion("critical_type <", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeLessThanOrEqualTo(String value) {
            addCriterion("critical_type <=", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeLike(String value) {
            addCriterion("critical_type like", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeNotLike(String value) {
            addCriterion("critical_type not like", value, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeIn(List<String> values) {
            addCriterion("critical_type in", values, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeNotIn(List<String> values) {
            addCriterion("critical_type not in", values, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeBetween(String value1, String value2) {
            addCriterion("critical_type between", value1, value2, "criticalType");
            return (Criteria) this;
        }

        public Criteria andCriticalTypeNotBetween(String value1, String value2) {
            addCriterion("critical_type not between", value1, value2, "criticalType");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Byte value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Byte value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Byte value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Byte value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Byte> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Byte> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCustomer1IsNull() {
            addCriterion("customer1 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer1IsNotNull() {
            addCriterion("customer1 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer1EqualTo(String value) {
            addCriterion("customer1 =", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1NotEqualTo(String value) {
            addCriterion("customer1 <>", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1GreaterThan(String value) {
            addCriterion("customer1 >", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1GreaterThanOrEqualTo(String value) {
            addCriterion("customer1 >=", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1LessThan(String value) {
            addCriterion("customer1 <", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1LessThanOrEqualTo(String value) {
            addCriterion("customer1 <=", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1Like(String value) {
            addCriterion("customer1 like", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1NotLike(String value) {
            addCriterion("customer1 not like", value, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1In(List<String> values) {
            addCriterion("customer1 in", values, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1NotIn(List<String> values) {
            addCriterion("customer1 not in", values, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1Between(String value1, String value2) {
            addCriterion("customer1 between", value1, value2, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer1NotBetween(String value1, String value2) {
            addCriterion("customer1 not between", value1, value2, "customer1");
            return (Criteria) this;
        }

        public Criteria andCustomer2IsNull() {
            addCriterion("customer2 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer2IsNotNull() {
            addCriterion("customer2 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer2EqualTo(String value) {
            addCriterion("customer2 =", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotEqualTo(String value) {
            addCriterion("customer2 <>", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2GreaterThan(String value) {
            addCriterion("customer2 >", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2GreaterThanOrEqualTo(String value) {
            addCriterion("customer2 >=", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2LessThan(String value) {
            addCriterion("customer2 <", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2LessThanOrEqualTo(String value) {
            addCriterion("customer2 <=", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2Like(String value) {
            addCriterion("customer2 like", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotLike(String value) {
            addCriterion("customer2 not like", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2In(List<String> values) {
            addCriterion("customer2 in", values, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotIn(List<String> values) {
            addCriterion("customer2 not in", values, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2Between(String value1, String value2) {
            addCriterion("customer2 between", value1, value2, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotBetween(String value1, String value2) {
            addCriterion("customer2 not between", value1, value2, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer3IsNull() {
            addCriterion("customer3 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer3IsNotNull() {
            addCriterion("customer3 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer3EqualTo(String value) {
            addCriterion("customer3 =", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotEqualTo(String value) {
            addCriterion("customer3 <>", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3GreaterThan(String value) {
            addCriterion("customer3 >", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3GreaterThanOrEqualTo(String value) {
            addCriterion("customer3 >=", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3LessThan(String value) {
            addCriterion("customer3 <", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3LessThanOrEqualTo(String value) {
            addCriterion("customer3 <=", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3Like(String value) {
            addCriterion("customer3 like", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotLike(String value) {
            addCriterion("customer3 not like", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3In(List<String> values) {
            addCriterion("customer3 in", values, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotIn(List<String> values) {
            addCriterion("customer3 not in", values, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3Between(String value1, String value2) {
            addCriterion("customer3 between", value1, value2, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotBetween(String value1, String value2) {
            addCriterion("customer3 not between", value1, value2, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer4IsNull() {
            addCriterion("customer4 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer4IsNotNull() {
            addCriterion("customer4 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer4EqualTo(String value) {
            addCriterion("customer4 =", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotEqualTo(String value) {
            addCriterion("customer4 <>", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4GreaterThan(String value) {
            addCriterion("customer4 >", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4GreaterThanOrEqualTo(String value) {
            addCriterion("customer4 >=", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4LessThan(String value) {
            addCriterion("customer4 <", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4LessThanOrEqualTo(String value) {
            addCriterion("customer4 <=", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4Like(String value) {
            addCriterion("customer4 like", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotLike(String value) {
            addCriterion("customer4 not like", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4In(List<String> values) {
            addCriterion("customer4 in", values, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotIn(List<String> values) {
            addCriterion("customer4 not in", values, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4Between(String value1, String value2) {
            addCriterion("customer4 between", value1, value2, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotBetween(String value1, String value2) {
            addCriterion("customer4 not between", value1, value2, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer5IsNull() {
            addCriterion("customer5 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer5IsNotNull() {
            addCriterion("customer5 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer5EqualTo(String value) {
            addCriterion("customer5 =", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5NotEqualTo(String value) {
            addCriterion("customer5 <>", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5GreaterThan(String value) {
            addCriterion("customer5 >", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5GreaterThanOrEqualTo(String value) {
            addCriterion("customer5 >=", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5LessThan(String value) {
            addCriterion("customer5 <", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5LessThanOrEqualTo(String value) {
            addCriterion("customer5 <=", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5Like(String value) {
            addCriterion("customer5 like", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5NotLike(String value) {
            addCriterion("customer5 not like", value, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5In(List<String> values) {
            addCriterion("customer5 in", values, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5NotIn(List<String> values) {
            addCriterion("customer5 not in", values, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5Between(String value1, String value2) {
            addCriterion("customer5 between", value1, value2, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer5NotBetween(String value1, String value2) {
            addCriterion("customer5 not between", value1, value2, "customer5");
            return (Criteria) this;
        }

        public Criteria andCustomer6IsNull() {
            addCriterion("customer6 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer6IsNotNull() {
            addCriterion("customer6 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer6EqualTo(String value) {
            addCriterion("customer6 =", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6NotEqualTo(String value) {
            addCriterion("customer6 <>", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6GreaterThan(String value) {
            addCriterion("customer6 >", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6GreaterThanOrEqualTo(String value) {
            addCriterion("customer6 >=", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6LessThan(String value) {
            addCriterion("customer6 <", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6LessThanOrEqualTo(String value) {
            addCriterion("customer6 <=", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6Like(String value) {
            addCriterion("customer6 like", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6NotLike(String value) {
            addCriterion("customer6 not like", value, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6In(List<String> values) {
            addCriterion("customer6 in", values, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6NotIn(List<String> values) {
            addCriterion("customer6 not in", values, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6Between(String value1, String value2) {
            addCriterion("customer6 between", value1, value2, "customer6");
            return (Criteria) this;
        }

        public Criteria andCustomer6NotBetween(String value1, String value2) {
            addCriterion("customer6 not between", value1, value2, "customer6");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ele_shikigami
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 12 15:38:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ele_shikigami
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}