package me.ele.napos.mybatis.model;

public class EleShikigami {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.name
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.cv
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String cv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.attack_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String attackNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.attack_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String attackType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.lives_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String livesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.lives_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String livesType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.defense_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String defenseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.defense_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String defenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.speed_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String speedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.speed_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String speedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.critical_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String criticalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.critical_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String criticalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.is_delete
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.customer1
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.customer2
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.customer3
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.customer4
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.customer5
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_shikigami.customer6
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.id
     *
     * @return the value of ele_shikigami.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.id
     *
     * @param id the value for ele_shikigami.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.name
     *
     * @return the value of ele_shikigami.name
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.name
     *
     * @param name the value for ele_shikigami.name
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.type
     *
     * @return the value of ele_shikigami.type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.type
     *
     * @param type the value for ele_shikigami.type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.cv
     *
     * @return the value of ele_shikigami.cv
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCv() {
        return cv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.cv
     *
     * @param cv the value for ele_shikigami.cv
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCv(String cv) {
        this.cv = cv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.attack_num
     *
     * @return the value of ele_shikigami.attack_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getAttackNum() {
        return attackNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.attack_num
     *
     * @param attackNum the value for ele_shikigami.attack_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setAttackNum(String attackNum) {
        this.attackNum = attackNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.attack_type
     *
     * @return the value of ele_shikigami.attack_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getAttackType() {
        return attackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.attack_type
     *
     * @param attackType the value for ele_shikigami.attack_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setAttackType(String attackType) {
        this.attackType = attackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.lives_num
     *
     * @return the value of ele_shikigami.lives_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getLivesNum() {
        return livesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.lives_num
     *
     * @param livesNum the value for ele_shikigami.lives_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setLivesNum(String livesNum) {
        this.livesNum = livesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.lives_type
     *
     * @return the value of ele_shikigami.lives_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getLivesType() {
        return livesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.lives_type
     *
     * @param livesType the value for ele_shikigami.lives_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setLivesType(String livesType) {
        this.livesType = livesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.defense_num
     *
     * @return the value of ele_shikigami.defense_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getDefenseNum() {
        return defenseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.defense_num
     *
     * @param defenseNum the value for ele_shikigami.defense_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setDefenseNum(String defenseNum) {
        this.defenseNum = defenseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.defense_type
     *
     * @return the value of ele_shikigami.defense_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getDefenseType() {
        return defenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.defense_type
     *
     * @param defenseType the value for ele_shikigami.defense_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setDefenseType(String defenseType) {
        this.defenseType = defenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.speed_num
     *
     * @return the value of ele_shikigami.speed_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getSpeedNum() {
        return speedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.speed_num
     *
     * @param speedNum the value for ele_shikigami.speed_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setSpeedNum(String speedNum) {
        this.speedNum = speedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.speed_type
     *
     * @return the value of ele_shikigami.speed_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getSpeedType() {
        return speedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.speed_type
     *
     * @param speedType the value for ele_shikigami.speed_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setSpeedType(String speedType) {
        this.speedType = speedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.critical_num
     *
     * @return the value of ele_shikigami.critical_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCriticalNum() {
        return criticalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.critical_num
     *
     * @param criticalNum the value for ele_shikigami.critical_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCriticalNum(String criticalNum) {
        this.criticalNum = criticalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.critical_type
     *
     * @return the value of ele_shikigami.critical_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCriticalType() {
        return criticalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.critical_type
     *
     * @param criticalType the value for ele_shikigami.critical_type
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCriticalType(String criticalType) {
        this.criticalType = criticalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.is_delete
     *
     * @return the value of ele_shikigami.is_delete
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.is_delete
     *
     * @param isDelete the value for ele_shikigami.is_delete
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.customer1
     *
     * @return the value of ele_shikigami.customer1
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer1() {
        return customer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.customer1
     *
     * @param customer1 the value for ele_shikigami.customer1
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer1(String customer1) {
        this.customer1 = customer1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.customer2
     *
     * @return the value of ele_shikigami.customer2
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer2() {
        return customer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.customer2
     *
     * @param customer2 the value for ele_shikigami.customer2
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer2(String customer2) {
        this.customer2 = customer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.customer3
     *
     * @return the value of ele_shikigami.customer3
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer3() {
        return customer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.customer3
     *
     * @param customer3 the value for ele_shikigami.customer3
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer3(String customer3) {
        this.customer3 = customer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.customer4
     *
     * @return the value of ele_shikigami.customer4
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer4() {
        return customer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.customer4
     *
     * @param customer4 the value for ele_shikigami.customer4
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer4(String customer4) {
        this.customer4 = customer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.customer5
     *
     * @return the value of ele_shikigami.customer5
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer5() {
        return customer5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.customer5
     *
     * @param customer5 the value for ele_shikigami.customer5
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer5(String customer5) {
        this.customer5 = customer5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_shikigami.customer6
     *
     * @return the value of ele_shikigami.customer6
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer6() {
        return customer6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_shikigami.customer6
     *
     * @param customer6 the value for ele_shikigami.customer6
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer6(String customer6) {
        this.customer6 = customer6;
    }
}