package me.ele.napos.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class EleUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public EleUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNull() {
            addCriterion("employee_name is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNotNull() {
            addCriterion("employee_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameEqualTo(String value) {
            addCriterion("employee_name =", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotEqualTo(String value) {
            addCriterion("employee_name <>", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThan(String value) {
            addCriterion("employee_name >", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("employee_name >=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThan(String value) {
            addCriterion("employee_name <", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThanOrEqualTo(String value) {
            addCriterion("employee_name <=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLike(String value) {
            addCriterion("employee_name like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotLike(String value) {
            addCriterion("employee_name not like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIn(List<String> values) {
            addCriterion("employee_name in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotIn(List<String> values) {
            addCriterion("employee_name not in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameBetween(String value1, String value2) {
            addCriterion("employee_name between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotBetween(String value1, String value2) {
            addCriterion("employee_name not between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneIsNull() {
            addCriterion("employee_phone is null");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneIsNotNull() {
            addCriterion("employee_phone is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneEqualTo(String value) {
            addCriterion("employee_phone =", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNotEqualTo(String value) {
            addCriterion("employee_phone <>", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneGreaterThan(String value) {
            addCriterion("employee_phone >", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("employee_phone >=", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneLessThan(String value) {
            addCriterion("employee_phone <", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneLessThanOrEqualTo(String value) {
            addCriterion("employee_phone <=", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneLike(String value) {
            addCriterion("employee_phone like", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNotLike(String value) {
            addCriterion("employee_phone not like", value, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneIn(List<String> values) {
            addCriterion("employee_phone in", values, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNotIn(List<String> values) {
            addCriterion("employee_phone not in", values, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneBetween(String value1, String value2) {
            addCriterion("employee_phone between", value1, value2, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNotBetween(String value1, String value2) {
            addCriterion("employee_phone not between", value1, value2, "employeePhone");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailIsNull() {
            addCriterion("employee_email is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailIsNotNull() {
            addCriterion("employee_email is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailEqualTo(String value) {
            addCriterion("employee_email =", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotEqualTo(String value) {
            addCriterion("employee_email <>", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailGreaterThan(String value) {
            addCriterion("employee_email >", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailGreaterThanOrEqualTo(String value) {
            addCriterion("employee_email >=", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailLessThan(String value) {
            addCriterion("employee_email <", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailLessThanOrEqualTo(String value) {
            addCriterion("employee_email <=", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailLike(String value) {
            addCriterion("employee_email like", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotLike(String value) {
            addCriterion("employee_email not like", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailIn(List<String> values) {
            addCriterion("employee_email in", values, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotIn(List<String> values) {
            addCriterion("employee_email not in", values, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailBetween(String value1, String value2) {
            addCriterion("employee_email between", value1, value2, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotBetween(String value1, String value2) {
            addCriterion("employee_email not between", value1, value2, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentIsNull() {
            addCriterion("employee_department is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentIsNotNull() {
            addCriterion("employee_department is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentEqualTo(String value) {
            addCriterion("employee_department =", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotEqualTo(String value) {
            addCriterion("employee_department <>", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentGreaterThan(String value) {
            addCriterion("employee_department >", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("employee_department >=", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentLessThan(String value) {
            addCriterion("employee_department <", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentLessThanOrEqualTo(String value) {
            addCriterion("employee_department <=", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentLike(String value) {
            addCriterion("employee_department like", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotLike(String value) {
            addCriterion("employee_department not like", value, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentIn(List<String> values) {
            addCriterion("employee_department in", values, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotIn(List<String> values) {
            addCriterion("employee_department not in", values, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentBetween(String value1, String value2) {
            addCriterion("employee_department between", value1, value2, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andEmployeeDepartmentNotBetween(String value1, String value2) {
            addCriterion("employee_department not between", value1, value2, "employeeDepartment");
            return (Criteria) this;
        }

        public Criteria andWechatIsNull() {
            addCriterion("wechat is null");
            return (Criteria) this;
        }

        public Criteria andWechatIsNotNull() {
            addCriterion("wechat is not null");
            return (Criteria) this;
        }

        public Criteria andWechatEqualTo(String value) {
            addCriterion("wechat =", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotEqualTo(String value) {
            addCriterion("wechat <>", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatGreaterThan(String value) {
            addCriterion("wechat >", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatGreaterThanOrEqualTo(String value) {
            addCriterion("wechat >=", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatLessThan(String value) {
            addCriterion("wechat <", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatLessThanOrEqualTo(String value) {
            addCriterion("wechat <=", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatLike(String value) {
            addCriterion("wechat like", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotLike(String value) {
            addCriterion("wechat not like", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatIn(List<String> values) {
            addCriterion("wechat in", values, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotIn(List<String> values) {
            addCriterion("wechat not in", values, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatBetween(String value1, String value2) {
            addCriterion("wechat between", value1, value2, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotBetween(String value1, String value2) {
            addCriterion("wechat not between", value1, value2, "wechat");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPassportNumIsNull() {
            addCriterion("passport_num is null");
            return (Criteria) this;
        }

        public Criteria andPassportNumIsNotNull() {
            addCriterion("passport_num is not null");
            return (Criteria) this;
        }

        public Criteria andPassportNumEqualTo(String value) {
            addCriterion("passport_num =", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumNotEqualTo(String value) {
            addCriterion("passport_num <>", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumGreaterThan(String value) {
            addCriterion("passport_num >", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumGreaterThanOrEqualTo(String value) {
            addCriterion("passport_num >=", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumLessThan(String value) {
            addCriterion("passport_num <", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumLessThanOrEqualTo(String value) {
            addCriterion("passport_num <=", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumLike(String value) {
            addCriterion("passport_num like", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumNotLike(String value) {
            addCriterion("passport_num not like", value, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumIn(List<String> values) {
            addCriterion("passport_num in", values, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumNotIn(List<String> values) {
            addCriterion("passport_num not in", values, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumBetween(String value1, String value2) {
            addCriterion("passport_num between", value1, value2, "passportNum");
            return (Criteria) this;
        }

        public Criteria andPassportNumNotBetween(String value1, String value2) {
            addCriterion("passport_num not between", value1, value2, "passportNum");
            return (Criteria) this;
        }

        public Criteria andCustomer2IsNull() {
            addCriterion("customer2 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer2IsNotNull() {
            addCriterion("customer2 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer2EqualTo(String value) {
            addCriterion("customer2 =", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotEqualTo(String value) {
            addCriterion("customer2 <>", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2GreaterThan(String value) {
            addCriterion("customer2 >", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2GreaterThanOrEqualTo(String value) {
            addCriterion("customer2 >=", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2LessThan(String value) {
            addCriterion("customer2 <", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2LessThanOrEqualTo(String value) {
            addCriterion("customer2 <=", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2Like(String value) {
            addCriterion("customer2 like", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotLike(String value) {
            addCriterion("customer2 not like", value, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2In(List<String> values) {
            addCriterion("customer2 in", values, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotIn(List<String> values) {
            addCriterion("customer2 not in", values, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2Between(String value1, String value2) {
            addCriterion("customer2 between", value1, value2, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer2NotBetween(String value1, String value2) {
            addCriterion("customer2 not between", value1, value2, "customer2");
            return (Criteria) this;
        }

        public Criteria andCustomer3IsNull() {
            addCriterion("customer3 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer3IsNotNull() {
            addCriterion("customer3 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer3EqualTo(String value) {
            addCriterion("customer3 =", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotEqualTo(String value) {
            addCriterion("customer3 <>", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3GreaterThan(String value) {
            addCriterion("customer3 >", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3GreaterThanOrEqualTo(String value) {
            addCriterion("customer3 >=", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3LessThan(String value) {
            addCriterion("customer3 <", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3LessThanOrEqualTo(String value) {
            addCriterion("customer3 <=", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3Like(String value) {
            addCriterion("customer3 like", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotLike(String value) {
            addCriterion("customer3 not like", value, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3In(List<String> values) {
            addCriterion("customer3 in", values, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotIn(List<String> values) {
            addCriterion("customer3 not in", values, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3Between(String value1, String value2) {
            addCriterion("customer3 between", value1, value2, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer3NotBetween(String value1, String value2) {
            addCriterion("customer3 not between", value1, value2, "customer3");
            return (Criteria) this;
        }

        public Criteria andCustomer4IsNull() {
            addCriterion("customer4 is null");
            return (Criteria) this;
        }

        public Criteria andCustomer4IsNotNull() {
            addCriterion("customer4 is not null");
            return (Criteria) this;
        }

        public Criteria andCustomer4EqualTo(String value) {
            addCriterion("customer4 =", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotEqualTo(String value) {
            addCriterion("customer4 <>", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4GreaterThan(String value) {
            addCriterion("customer4 >", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4GreaterThanOrEqualTo(String value) {
            addCriterion("customer4 >=", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4LessThan(String value) {
            addCriterion("customer4 <", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4LessThanOrEqualTo(String value) {
            addCriterion("customer4 <=", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4Like(String value) {
            addCriterion("customer4 like", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotLike(String value) {
            addCriterion("customer4 not like", value, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4In(List<String> values) {
            addCriterion("customer4 in", values, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotIn(List<String> values) {
            addCriterion("customer4 not in", values, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4Between(String value1, String value2) {
            addCriterion("customer4 between", value1, value2, "customer4");
            return (Criteria) this;
        }

        public Criteria andCustomer4NotBetween(String value1, String value2) {
            addCriterion("customer4 not between", value1, value2, "customer4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ele_user
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 12 15:38:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}