package me.ele.napos.mybatis.model;

public class EleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.employee_name
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String employeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.employee_phone
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String employeePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.employee_email
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String employeeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.employee_department
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String employeeDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.wechat
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.id_card
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.address
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.passport_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String passportNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.customer2
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.customer3
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_user.customer4
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    private String customer4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.id
     *
     * @return the value of ele_user.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.id
     *
     * @param id the value for ele_user.id
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.employee_name
     *
     * @return the value of ele_user.employee_name
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.employee_name
     *
     * @param employeeName the value for ele_user.employee_name
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.employee_phone
     *
     * @return the value of ele_user.employee_phone
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.employee_phone
     *
     * @param employeePhone the value for ele_user.employee_phone
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.employee_email
     *
     * @return the value of ele_user.employee_email
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getEmployeeEmail() {
        return employeeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.employee_email
     *
     * @param employeeEmail the value for ele_user.employee_email
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setEmployeeEmail(String employeeEmail) {
        this.employeeEmail = employeeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.employee_department
     *
     * @return the value of ele_user.employee_department
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getEmployeeDepartment() {
        return employeeDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.employee_department
     *
     * @param employeeDepartment the value for ele_user.employee_department
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setEmployeeDepartment(String employeeDepartment) {
        this.employeeDepartment = employeeDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.wechat
     *
     * @return the value of ele_user.wechat
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.wechat
     *
     * @param wechat the value for ele_user.wechat
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.id_card
     *
     * @return the value of ele_user.id_card
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.id_card
     *
     * @param idCard the value for ele_user.id_card
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.address
     *
     * @return the value of ele_user.address
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.address
     *
     * @param address the value for ele_user.address
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.passport_num
     *
     * @return the value of ele_user.passport_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getPassportNum() {
        return passportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.passport_num
     *
     * @param passportNum the value for ele_user.passport_num
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setPassportNum(String passportNum) {
        this.passportNum = passportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.customer2
     *
     * @return the value of ele_user.customer2
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer2() {
        return customer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.customer2
     *
     * @param customer2 the value for ele_user.customer2
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer2(String customer2) {
        this.customer2 = customer2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.customer3
     *
     * @return the value of ele_user.customer3
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer3() {
        return customer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.customer3
     *
     * @param customer3 the value for ele_user.customer3
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer3(String customer3) {
        this.customer3 = customer3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_user.customer4
     *
     * @return the value of ele_user.customer4
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public String getCustomer4() {
        return customer4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_user.customer4
     *
     * @param customer4 the value for ele_user.customer4
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    public void setCustomer4(String customer4) {
        this.customer4 = customer4;
    }
}