package me.ele.napos.mybatis.dao;

import me.ele.napos.mybatis.annotations.SqlMapper;
import me.ele.napos.mybatis.model.EleUser;
import me.ele.napos.mybatis.model.EleUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@SqlMapper
public interface EleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int countByExample(EleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int deleteByExample(EleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int insert(EleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int insertSelective(EleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    List<EleUser> selectByExample(EleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    EleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") EleUser record, @Param("example") EleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int updateByExample(@Param("record") EleUser record, @Param("example") EleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int updateByPrimaryKeySelective(EleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_user
     *
     * @mbggenerated Wed Apr 12 15:38:16 CST 2017
     */
    int updateByPrimaryKey(EleUser record);
}